import type { PodWithRelations } from "@/types/database";

/**
 * Hand-authored fake pods for demoing the Match Feed / pod detail UI
 * without needing real Supabase data (e.g. screen-sharing, App Store
 * screenshots). Not wired into any live query — import DEMO_PODS directly
 * wherever a component needs pods to render, e.g.
 * `<MatchFeed pods={DEMO_PODS} />` in a throwaway demo page.
 */
export const DEMO_PODS: PodWithRelations[] = [
  {
    id: "demo-pod-1",
    user_id: "demo-user-1",
    game_key: "MTG",
    format_key: "COMMANDER",
    playstyle_key: "casual",
    power_tiers: [3, 4],
    type: "IRL",
    location_name: "Le Panda Roux",
    city: "paris",
    scheduled_at: null,
    max_players: 4,
    reserved_slots: 0,
    notes: "Bringing a Krenko goblins deck, happy to explain rules for newer players.",
    status: "ACTIVE",
    created_at: "2026-07-26T14:00:00.000Z",
    expires_at: "2026-07-26T20:00:00.000Z",
    matched_at: null,
    locked_at: null,
    recurring_table_id: null,
    auto_accept: false,
    store_name: null,
    profiles: {
      id: "demo-user-1",
      updated_at: "2026-07-26T14:00:00.000Z",
      username: "Théo",
      discord_handle: "theo_mtg",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Theo",
      city: "paris",
      preferred_game: "MTG",
      preferred_format: "COMMANDER",
      preferred_playstyle: "casual",
      preferred_brackets: [3, 4],
      preferred_match_type: "IRL",
      preferred_location_name: "Le Panda Roux",
      preferred_max_players: 4,
      is_admin: false,
    },
    pod_joins: [
      {
        id: "demo-join-1",
        pod_id: "demo-pod-1",
        user_id: "demo-user-2",
        status: "ACCEPTED",
        joined_at: "2026-07-26T14:10:00.000Z",
        matched_notified_at: null,
        profiles: {
          id: "demo-user-2",
          updated_at: "2026-07-26T14:10:00.000Z",
          username: "Camille",
          discord_handle: "camille_tcg",
          avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Camille",
          city: "paris",
          preferred_game: "MTG",
          preferred_format: "COMMANDER",
          preferred_playstyle: "casual",
          preferred_brackets: [3, 4],
          preferred_match_type: "IRL",
          preferred_location_name: null,
          preferred_max_players: 4,
          is_admin: false,
        },
      },
    ],
  },
  {
    id: "demo-pod-2",
    user_id: "demo-user-3",
    game_key: "POKEMON",
    format_key: "STANDARD",
    playstyle_key: "competitive",
    power_tiers: null,
    type: "ONLINE",
    location_name: null,
    city: null,
    scheduled_at: "2026-07-27T18:30:00.000Z",
    max_players: 2,
    reserved_slots: 0,
    notes: null,
    status: "ACTIVE",
    created_at: "2026-07-26T12:00:00.000Z",
    expires_at: "2026-07-27T00:00:00.000Z",
    matched_at: null,
    locked_at: null,
    recurring_table_id: null,
    auto_accept: false,
    store_name: null,
    profiles: {
      id: "demo-user-3",
      updated_at: "2026-07-26T12:00:00.000Z",
      username: "Yanis",
      discord_handle: "yanis_ptcg",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Yanis",
      city: null,
      preferred_game: "POKEMON",
      preferred_format: "STANDARD",
      preferred_playstyle: "competitive",
      preferred_brackets: null,
      preferred_match_type: "ONLINE",
      preferred_location_name: null,
      preferred_max_players: 2,
      is_admin: false,
    },
    pod_joins: [],
  },
];
